---

# tasks file for osp.instance.delete
- name: delete instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    image: rhel-guest
    meta: "group={{ item.group }},deployment_name={{ item.deploy }}"
    flavor: m2.small
    security_groups: "{{ item.secgroup }}"
    key_name: ansible_ssh
    wait: yes
    state: absent
  loop: "{{ instances }}"
  register: instance_res

- name: output of result
  debug:
    verbosity: 2
    msg:
      - "results are {{ item.changed }}"
      - "results are {{ item.item.name }}"
      - "results are {{ item.server.vm_state }}"
  loop: "{{ instance_res.results }}"

