---

# tasks file for osp.instance.delete
- name: delete instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    image: rhel-guest
    meta: "group={{ item.group }},deployment_name={{ item.deploy }}"
    flavor: m2.small
    security_groups: "{{ item.secgroup }}"
    key_name: ansible_ssh
    wait: yes
    state: absent
  loop: "{{ instances }}"
  register: instance_res


- name: Delete floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    reuse: yes
    server: "{{ item.item.name }}"
    network: ext_network
    wait: true
    state: absent
    timeout: 180
  loop: "{{ instance_res.results }}"
  register: float_res
