- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: http://frontend1.{{ ec2_tag_guid }}.example.opentlc.com
      return_content: true
    register: webresult
    failed_when: "'Ansible has done its job' not in webresult.content"
