- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke

  - name: Get website
    uri:
      url: http://frontend1.627a.example.opentlc.com/ansible
      return_content: true
    register: webres
    failed_when: "'Ansible has done its job' not in webres.content"
    tags:
      - osp.smoke

