- name: Smoke Test 3 Tier application
  hosts: workstation
  become: true
  gather_facts: false
  tasks:
   - name: Fetch Instance Info
     os_server_info:
      cloud: ospcloud
      server: frontend
     register: result

   - name: connection test
     uri:
       url: http://{{ item.public_v4 }}
       return_content: true
     when: item.hostname == 'frontend'
     loop: "{{ result.openstack_servers }}"
     register: webresult
     failed_when: "'Ansible has done its job' not in webresult.content"
