- hosts: localhost
  become: yes
  vars:
    - iplist:
      - 10.10.10.4
      - 10.10.10.5
      - 10.10.10.8
      - 10.10.10.10
  tasks:
    - name: Wait for server to be available
      wait_for:
        host: "{{ item }}"
        port: 22
        search_regex: OpenSSH
        timeout: 600
      loop: "{{ iplist }}"
      delegate_to: localhost

